name: material_palette
description: >
  A collection of procedural material shader widgets for Flutter.
version: 0.2.0
homepage: https://br0nk.github.io/material_palette/
repository: https://github.com/br0nk/material_palette
issue_tracker: https://github.com/br0nk/material_palette/issues

topics:
  - shader
  - material
  - gpu
  - glsl
  - animation

environment:
  sdk: ^3.6.1
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  shaders:
    - lib/shaders/click_ripple.frag
    - lib/shaders/fbm_gradient.frag
    - lib/shaders/gritty_gradient.frag
    - lib/shaders/marble_smear.frag
    - lib/shaders/perlin_gradient.frag
    - lib/shaders/radial_fbm_gradient.frag
    - lib/shaders/radial_gritty_gradient.frag
    - lib/shaders/radial_perlin_gradient.frag
    - lib/shaders/radial_simplex_gradient.frag
    - lib/shaders/radial_turbulence_gradient.frag
    - lib/shaders/radial_voronoi_gradient.frag
    - lib/shaders/radial_voronoise_gradient.frag
    - lib/shaders/ripple.frag
    - lib/shaders/simplex_gradient.frag
    - lib/shaders/turbulence_gradient.frag
    - lib/shaders/voronoi_gradient.frag
    - lib/shaders/voronoise_gradient.frag
